### ISSUE TITLE
Loopback soap integration run failing in API Explorer

### ISSUE THREAD

**Issue by skaluva** [loopbackio/loopback.io#929]
https://loopback.io/doc/en/lb4/Connecting-to-SOAP.html

I followed above tutorial and able to succesfully integrate one of our web service as API Explorer.
But when i run API in APIExplorer, its always giving me error 406 - Unacceptable.
I copied the cURL given in API Explorer and ran in Postman. 
Observed that API Explorer adding "--header 'Accept: text/plain'", when i remove the same in Postman, its giving response as expected.

Below is the cURL given in API Explorer for my API:

```
> curl -X POST --header 'Content-Type: text/xml' --header 'Accept: text/plain' -d '<?xml version="1.0"?> \ 
>  <getLanguagesByFE> \ 
>    <languagesRequest> \ 
>      <frontendId>pp</frontendId> \ 
>      <languageId>en_US</languageId> \ 
>    </languagesRequest> \ 
>  </getLanguagesByFE> \ 
>  ' 'http://localhost:3000/api/CommonServiceSoap11Binding/getLanguagesByFE'
```

**Response:**
```
Response Body Not Acceptable
Response Code 406
Response Headers
{
  "access-control-allow-credentials": "true",
  "access-control-allow-origin": "http://localhost:3000",
  "connection": "keep-alive",
  "content-length": "14",
  "content-type": "text/plain; charset=utf-8",
  "date": "Fri, 31 Jan 2020 07:26:04 GMT",
  "etag": "W/\"e-dqk0oyZuM+x+D21Lq3ZqYJ94/o4\"",
  "strict-transport-security": "max-age=0; includeSubDomains",
  "vary": "Origin, Accept-Encoding",
  "x-content-type-options": "nosniff",
  "x-download-options": "noopen",
  "x-frame-options": "DENY",
  "x-xss-protection": "1; mode=block"
}
```

Same cURL i imported into postman and getting same response if i don't remove the header "Accept". If i remove the header, getting response as expected. Please help me out.

**Comment by dhmlau** [comment]
@skaluva, I think it's better to call the SOAP service as the service proxy, as shown in https://loopback.io/doc/en/lb4/Calling-other-APIs-and-web-services.html. 
I also have a running app: https://github.com/dhmlau/loopback4-external-apis.

Will try to see if [this docs](https://loopback.io/doc/en/lb4/Connecting-to-SOAP.html) is applicable to LB3 only.

**Comment by skaluva** [comment]
@dhmlau  Thanks for the reply. But i have 100s of APIs in a webservice and i have multiple webservices like that. In the approach you suggested, i need to input all API details. But whatever tutorial i followed it automatically generates all API implementations without much effort.   As postman works nicely by removing the Accept Header, i think it is something to do with API Explorer only to correct it.

**Comment by dhmlau** [comment]
Thanks @skaluva  for your explanation.
@hacksparrow, could you please take a look when you're available? Thanks.

**Comment by skaluva** [comment]
@dhmlau @hacksparrow any plans to take up this? This is the only bug stopping me integrating my SOAP webservices :(

**Comment by hacksparrow** [comment]
@skaluva if you can share a simple app which reproduces this promlem, I can take a look at this issue today.

**Comment by dhmlau** [comment]
@skaluva, how does your controller for that endpoint look like?
If the endpoint is expecting content type to be `text/xml`, you might want to do the following:
```
async create(
    @requestBody({
      content: {
        'text/xml': { // <----- change the content type here. 
          schema: Object
        },
      },
    })
    customer: Omit<Customer, 'custId'>,
  ): Promise<Customer> {
    return this.customerRepository.create(customer);
  }
```
I've tried the above solution to call the endpoint from API Explorer, the curl command contains `-H "Content-Type: text/xml"`.

Please give it a try.  Thanks.

**Comment by dhmlau** [comment]
@skaluva, we believe we've addressed your question. I'd like to close this issue now, please feel free to open a new issue if you have other questions. Thanks.

**Comment by skaluva** [comment]
@dhmlau 
Apologies for the late reply. Still not working. If i select "text/xml" from the content type drop down in API, It is still adding "text/plain" to the headers list. Not sure why. PFA screenshots for your reference.

![image](https://user-images.githubusercontent.com/2105229/84007935-b7a95700-a98e-11ea-9da5-6509740f97fa.png)
![image](https://user-images.githubusercontent.com/2105229/84007955-c132bf00-a98e-11ea-9f68-5c77bb85fd9d.png)
